ip: '10.20.30.60'
ram: 2048
proc: 1
box_name: 'saucy64'
box_url: 'http://brennovich.s3.amazonaws.com/saucy64_vmware_fusion.box'
vm_provider: vmw
forwards:
synced_folders:
  projects:
    host_path: '../www'
    guest_path: '/home/vagrant/www'
    guest_path_nfs: '/home/vagrant/www-nfs'
    owner: 'vagrant'
    group: 'vagrant'
    extra: ['dmode=775', 'fmode=775']
  db_dump:
    host_path: '../dump'
    guest_path: '/home/vagrant/dump'
    guest_path_nfs: '/home/vagrant/dump-nfs'
    owner: 'vagrant'
    group: 'vagrant'
    extra: ['dmode=775', 'fmode=775']
  logs:
    host_path: '../logs'
    guest_path: '/home/vagrant/logs'
    guest_path_nfs: '/home/vagrant/logs-nfs'
    owner: 'vagrant'
    group: 'vagrant'
    extra: ['dmode=775', 'fmode=775']
  scripts:
    host_path: '../scripts'
    guest_path: '/home/vagrant/scripts'
    guest_path_nfs: '/home/vagrant/scripts-nfs'
    owner: 'vagrant'
    group: 'vagrant'
    extra: ['dmode=775', 'fmode=775']
