# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

def symbolize_keys(hash)
  hash.inject({}){|result, (key, value)|
    new_key = case key
              when String then key.to_sym
              else key
              end
    new_value = case value
                when Hash then symbolize_keys(value)
                else value
                end
    result[new_key] = new_value
    result
  }
end

settings = YAML::load_file "settings.yml"
settings = symbolize_keys(settings)

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = settings[:box_name]
  config.vm.box_url = settings[:box_url]

  if settings[:forwards]
    settings[:forwards].each do |fname, forward|
      config.vm.network :forwarded_port, guest: forward[:from], host: forward[:to]
    end
  end


  config.vm.provider "virtualbox" do |v|
    v.customize [ "modifyvm", :id, "--cpus", settings[:proc] ]
    v.customize [ "modifyvm", :id, "--memory", settings[:ram] ]
  end

  config.vm.network :private_network, ip: settings[:ip]
  config.vm.synced_folder "conf/", "/srv"

  if settings[:synced_folders]
    settings[:synced_folders].each do |sf_name, sf|
      config.vm.synced_folder sf[:host_path], sf[:guest_path], :nfs => true
    end
  end

  config.vm.provision :salt do |salt|

    salt.install_args = "v0.16.0"
    salt.install_type = "git"
    salt.minion_config = "conf/minion"
    salt.run_highstate = true
    salt.verbose = true

  end

end
